name: esmc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - pip
  - numpy>=1.24.0
  - pandas>=1.5.0
  - scikit-learn>=1.3.0
  - tqdm>=4.65.0
  - pip:
    - transformers>=4.30.0
    - esm>=2.0.0