#!/bin/bash

echo "ESM Package Installation Guide"
echo "=============================="
echo ""
echo "You have two options for installing ESM packages:"
echo ""
echo "Option 1: Install the new ESM package (from EvolutionaryScale)"
echo "This supports ESM-C and newer models:"
echo "  pip install esm"
echo ""
echo "Option 2: Install fair-esm package (from Facebook AI Research)" 
echo "This supports ESM-2 and ESM-1b models:"
echo "  pip install fair-esm"
echo ""
echo "Option 3: Install both (recommended for maximum compatibility):"
echo "  pip install esm fair-esm"
echo ""
echo "Other required packages:"
echo "  pip install torch numpy tqdm"
echo ""
echo "Full installation command:"
echo "  pip install torch numpy tqdm esm fair-esm"
echo ""
echo "Note: The code will automatically detect which package you have installed"
echo "and use the appropriate API."